name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ECR_REPO: ${{ steps.tfoutputs.outputs.ecr_repo }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=aws-terraform init

      - name: Terraform Apply
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: terraform -chdir=aws-terraform apply -auto-approve

      - name: Save Terraform Outputs
        id: tfoutputs
        run: |
          ECR_URL=$(terraform -chdir=aws-terraform output -raw ecr_repo)
          echo "::set-output name=ecr_repo::$ECR_URL"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set ECR Repo Environment Variable
        run: echo "ECR_REPO=${{ needs.terraform.outputs.ECR_REPO }}" >> $GITHUB_ENV

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build Docker Image
        run: docker build -t ${{ env.ECR_REPO }}:latest .

      - name: Push Docker Image
        run: docker push ${{ env.ECR_REPO }}:latest
