name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform -chdir=aws-terraform init

      - name: Terraform Apply
        run: terraform -chdir=aws-terraform apply -auto-approve

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get ECR Repo URL
        id: ecr
        run: echo "REPO_URL=$(terraform -chdir=aws-terraform output -raw ecr_repo)" >> $GITHUB_ENV

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.REPO_URL }}

      - name: Build Docker Image
        run: docker build -t ${{ env.REPO_URL }}:latest .

      - name: Push to ECR
        run: docker push ${{ env.REPO_URL }}:latest
