name: infra-and-deploy

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

     
