name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=aws-terraform init

      - name: Terraform Apply
        run: terraform -chdir=aws-terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tfoutputs
        run: |
          echo "ECR_REPO_URL=$(terraform -chdir=aws-terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
          echo "ECR_REPO_URL: $ECR_REPO_URL"

      - name: Login to ECR
        run: |
          echo "Logging in to Amazon ECR..."
          if [ -z "$ECR_REPO_URL" ]; then
            echo "❌ ERROR: ECR_REPO_URL is empty. Check Terraform output."
            exit 1
          fi
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REPO_URL:$IMAGE_TAG .
          docker push $ECR_REPO_URL:$IMAGE_TAG
