name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Application JAR
        run: mvn -DskipTests package

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform -chdir=aws-terraform init

      - name: Apply Terraform
        run: terraform -chdir=aws-terraform apply -auto-approve

      - name: Get ECR Repo URL
        run: |
          ECR_REPO=$(terraform -chdir=aws-terraform output -raw ecr_repo)
          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV

      - name: Log in to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build Docker Image
        run: docker build -t ${{ env.ECR_REPO }}:latest .

      - name: Push Docker Image
        run: docker push ${{ env.ECR_REPO }}:latest
